### ISSUE TITLE
Taking into account Fresnel Losses

### ISSUE THREAD

**Issue by timk110** [NickKarpowicz/LightwaveExplorer#41]
Hi

I am working on a two crystal system for fourth harmonic generation of a 1030nm fundamental (second harmonic in the first crystal followed by second harmonic of that in the second crystal). I want to make sure that Fresnel reflections at the interfaces are being taken into account correctly. As far as I can tell running the following sequence in LWE (3D Radial Symmetry propagation)

Air-BiBO-Air-BBO-Air
nonlinear(24,0,0,100,500)
nonlinear(4,166.6,90,1000,500)
nonlinear(24,0,0,100,500)
nonlinear(1,50,90,300,500)
nonlinear(24,0,0,100,500)

yields near identical results to 

BiBO-BBO
nonlinear(4,166.6,90,1000,500)
nonlinear(1,50,90,300,500)

Do I have to add the fresnel losses manually (i.e altering the pulse energies with a spectral filter between crystals) or am I not using the simulation correctly? 

Thanks,

Tim

**Comment by NickKarpowicz** [comment]
Hi there!
Yes, in the modes that use the unidirectional pulse propagation equation, the Fresnel losses aren't included. I started doing this automatically, but then changed my mind early in the design because I realized that usually we use crystals with antireflection coatings, so doing nothing was a better approximation that applying the full Fresnel loss.

Of course that does mean that the transmission is overestimated, so next step is what to replace it with.

If you just need a small, fairly uniform loss, you can probably approximate that pretty well with a simple filter function. If you need to do it more precisely, I'd use the applyOptic function. With this, you first load a text file (using the second button from the right in the row of sequence buttons), which should have three columns, Wavelength (nm) | Transmission (0.0 to 1.0) | Phase (rad). When you load a file, it will tell you which position in the database it is. In your sequence, you can apply it with loadOptic(N) where N is its index.

Note that you need the latest version for the loading optics button to be there!

I hope this helps!

Best wishes,
Nick

**Comment by timk110** [comment]
Hi Nick,

That makes a lot of sense! I will give this a go and see how I get on.

Cheers,

Tim
